### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Capital_Bikeshare_Analysis#33]
@Mikeymice @EvanYathon 
Your project looks great! So well done on Milestone 1! Here are some remaining issues:

**About report:**
- [ ] Do not add Figure numbers and captions as regular text under the figures. You can use `include_graphics()` to read in the figure and add figure caption with `fig.cap` in the chunk options.

**About the main readme**
- [ ] Add version information for dependencies.
- [ ] There are still some statements with future tense. Try to get rid of all the proposal-type statements in your readme. 

**Suggestions:**
- You can present the variables on the main readme with a tabular format. Variables in one column and explanations in another column. I think it can be easier to read.
- Keep all cleaned/wrangled data in `results/` folder rather than `data/` folder.

**Comment by EvanYathon** [comment]
Fixed report captions using `include_graphics()` in [this commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/9168a75e1b22282ce798069135e36255586917cc)

**Comment by Mikeymice** [comment]
moved cleaned data to result folder [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/b63a2c9a410668628669c8a5050943daebc3080b)

updated with table and corrected tense in README [commit](https://github.com/UBC-MDS/Capital_Bikeshare_Analysis/commit/1e61e7a3a6c0364f52140d35878fabbc2e5dc084)
