### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by Mikeymice** [UBC-MDS/Capital_Bikeshare_Analysis#8]
## TO DO LIST
> just a reminder what we should do for the future 

- [x] create Proposal
- [x] Load csv
- [x] create release by Nov 17, 6PM
- [x] Tidy Data
- [x] Extract Year, Month, Day 
- [x] Introduce Label for High, Mid , Low Rental Categories
- [x] Create visualization 
- [x] Create Decision Tree and fit
- [x] Obtain Accuracy Score
- [x] Save feature importance to csv
- [x] Create top predictors visualization
- [x] Create Report
